### ISSUE TITLE
Add screenshot to README

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-view#3]
Sometimes a picture is worth a thousand words. If micro-infra-view looks at least as effective as an old nodes representation it would be useful (to convince undecided and gather new users) to put a screenshot (animated GIF?) to README.

**Comment by piotrpietrzak** [comment]
![zrzut ekranu 2015-08-12 o 23 40 30](https://cloud.githubusercontent.com/assets/1497967/9237550/db33299a-414b-11e5-8911-37a99d48ad15.png)

**Comment by piotrpietrzak** [comment]
I can't prepare animated gif, but static screenshot was added.
